<script src="https://cdn.jsdelivr.net/gh/imabutahersiddik/erath@main/public/js/crypto.js"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<script src="https://cdn.jsdelivr.net/gh/mladenplavsic/bootstrap-navbar-sidebar@master/docs/docs.js"></script>
<script async defer src="https://buttons.github.io/buttons.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"></script>
<script src="https://code.iconify.design/2/2.0.3/iconify.min.js"></script>
 <script defer src="https://erath.vercel.app/_vercel/insights/script.js"></script>
 <script src="https://cdn.jsdelivr.net/gh/imabutahersiddik/Erath@main/public/js/ai.js"></script>
<script src="https://cdn.jsdelivr.net/gh/imabutahersiddik/Erath@main/public/js/sensor.js"></script>